"""

Example: List all available JSONPlaceholder objects

This example demonstrates discovery using list_objects().


🤖 AUTO-GENERATED by Driver Creator Agent
"""

from jsonplaceholder_driver import JsonplaceholderDriver



def main():
    # Initialize client from environment variables
    client = JsonplaceholderDriver.from_env()

    try:
        
        # Discover available objects
        print("Discovering JSONPlaceholder objects...")
        objects = client.list_objects()

        print(f"\\nFound {len(objects)} objects:")
        for i, obj in enumerate(objects, 1):
            print(f"  {i}. {obj}")

        # Show capabilities
        print("\\n" + "="*60)
        capabilities = client.get_capabilities()
        print("Driver Capabilities:")
        print(f"  Read operations: {capabilities.read}")
        print(f"  Write operations: {capabilities.write}")
        
        print(f"  Pagination: {capabilities.pagination.value}")

        

    finally:
        # Always close the client
        client.close()
        print("\\nDone!")


if __name__ == "__main__":
    main()