"""
JSONPlaceholder Driver

REST driver for JSONPlaceholder integration.

🤖 AUTO-GENERATED by Driver Creator Agent
📅 Generated: now
"""

__version__ = "1.0.0"

from .client import JsonplaceholderDriver
from .exceptions import *

__all__ = ["JsonplaceholderDriver", "DriverError", "AuthenticationError", "QuerySyntaxError", "RateLimitError"]