"""
Open-Meteo Driver

REST driver for Open-Meteo integration.

🤖 AUTO-GENERATED by Driver Creator Agent
📅 Generated: now
"""

__version__ = "1.0.0"

from .client import OpenMeteoDriver
from .exceptions import *

__all__ = ["OpenMeteoDriver", "DriverError", "AuthenticationError", "QuerySyntaxError", "RateLimitError"]