"""
Open-Meteo Driver - Exception Hierarchy

Structured exceptions for Open-Meteo driver, following Driver Design v2.0 spec.

🤖 AUTO-GENERATED by Driver Creator Agent
"""

from typing import Optional, Dict, Any


class DriverError(Exception):
    """Base exception for all driver errors"""

    def __init__(self, message: str, details: Optional[Dict[str, Any]] = None):
        super().__init__(message)
        self.message = message
        self.details = details or {}

    def __str__(self):
        """Return descriptive error message for agent"""
        return f"{self.__class__.__name__}: {self.message}"


class AuthenticationError(DriverError):
    """
    Invalid credentials or API key.

    Agent should:
    - Inform user to check credentials
    - Check .env file exists and has correct keys
    """
    pass


class ConnectionError(DriverError):
    """
    Cannot reach API (network issue, API down).

    Agent should:
    - Inform user API is unreachable
    - Suggest checking api_url configuration
    - Wait and retry later
    """
    pass


class ObjectNotFoundError(DriverError):
    """
    Requested object/table doesn't exist.

    Agent should:
    - Call list_objects() to see what's available
    - Suggest similar object names (fuzzy match)
    """
    pass


class FieldNotFoundError(DriverError):
    """
    Requested field doesn't exist on object.

    Agent should:
    - Call get_fields(object_name) to see available fields
    - Suggest similar field names
    """
    pass


class QuerySyntaxError(DriverError):
    """
    Invalid query syntax.

    Agent should:
    - Fix query syntax based on error message
    - Consult driver README for query language rules
    - Regenerate query
    """
    pass


class RateLimitError(DriverError):
    """
    API rate limit exceeded (after automatic retries).

    Driver automatically retries with exponential backoff.
    This exception is only raised after max_retries exhausted.

    Agent should:
    - Inform user of rate limit
    - Suggest reducing batch size or adding delays
    - Show retry_after seconds
    """
    pass


class ValidationError(DriverError):
    """
    Data validation failed (for write operations).

    Note: Driver does NOT validate input by default.
    This is only raised when API returns validation errors.

    Agent should:
    - Check required fields are present
    - Fix data types
    - Regenerate create/update call
    """
    pass


class TimeoutError(DriverError):
    """
    Request timed out.

    Agent should:
    - Inform user
    - Suggest increasing timeout parameter
    - Retry with smaller dataset
    """
    pass