"""

Example: Query data from Open-Meteo

This example demonstrates querying data with discovery-first approach.


🤖 AUTO-GENERATED by Driver Creator Agent
"""

from open_meteo_driver import OpenMeteoDriver
import json


def main():
    # Initialize client from environment variables
    client = OpenMeteoDriver.from_env()

    try:
        
        # Step 1: Discover schema (discovery-first approach)
        print("Discovering Open-Meteo schema...")
        objects = client.list_objects()
        print(f"Available objects: {', '.join(objects)}")

        # Select first object for demo
        if not objects:
            print("No objects available!")
            return

        object_name = objects[0]
        print(f"\\nQuerying object: {object_name}")

        # Get field schema
        fields = client.get_fields(object_name)
        available_fields = list(fields.keys())
        print(f"Available fields: {', '.join(available_fields[:5])}...")

        # Step 2: Build query dynamically from discovered schema
        
        # REST API - use read() method
        print(f"\\nReading data (limit=10)...")
        results = client.read(limit=10)
        

        # Step 3: Display results
        print(f"\\nFound {len(results)} records:")
        if results:
            # Show first record as sample
            print("\\nSample record:")
            print(json.dumps(results[0], indent=2))

            # Show summary
            print(f"\\nTotal records: {len(results)}")
        else:
            print("No records found.")

        

    finally:
        # Always close the client
        client.close()
        print("\\nDone!")


if __name__ == "__main__":
    main()